server:
  port: 6001
spring:
  # 配置业务使用的 Redis 连接
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 10s
  datasource:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 6000
      validation-timeout: 300
      idle-timeout: 6000
      login-timeout: 5
      max-lifetime: 600
      maximum-pool-size: 2
      minimum-idle: 2
      read-only: false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.155.235.122/web_start?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: guhGJUfwefe#123
knife4j:
  enableAggregation: true
  disk:
    enable: true
    routes:
      - name: 用户
        location: classpath:openapi/openapi.json
